JobPortal/Models/ManageJob.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ManageJob
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ManageJob()
        {
            this.jobseeks = new HashSet<jobseek>();
        }
    
        public int JobId { get; set; }
        public string JobName { get; set; }
        public string JobSkills { get; set; }
        public string JobExpirience { get; set; }
        public Nullable<bool> JobIsActive { get; set; }
        public string JobDocuments { get; set; }
        public string JobCreatedBy { get; set; }
        public string JobModifiedBy { get; set; }
        public Nullable<System.DateTime> JobCreatedDate { get; set; }
        public Nullable<System.DateTime> JobModifiedDate { get; set; }
        public Nullable<int> RefDepartmentId { get; set; }
        public Nullable<int> RefCityId { get; set; }
    
        public virtual CityMaster CityMaster { get; set; }
        public virtual Department Department { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<jobseek> jobseeks { get; set; }
    }
}

JobPortal/Areas/Admin/Controllers/ManageJobsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using JobPortal.Models;
using static JobPortal.FilterConfig;

namespace JobPortal.Areas.Admin.Controllers
{
    [AdminLoginFilter]
    public class ManageJobsController : Controller
    {
        private dbjobportalEntities1 db = new dbjobportalEntities1();

        // GET: Admin/ManageJobs
        public ActionResult Index()
        {
           
            var manageJobs = db.ManageJobs.Include(m => m.CityMaster).Include(m => m.Department);
            return View(manageJobs.ToList());
        }

        // GET: Admin/ManageJobs/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ManageJob manageJob = db.ManageJobs.Find(id);
            if (manageJob == null)
            {
                return HttpNotFound();
            }
            return View(manageJob);
        }

        // GET: Admin/ManageJobs/Create
        public ActionResult Create()
        {

            ViewBag.countryname = new SelectList(db.CountryMasters.ToList(), "CountryId", "CountryName");
            ViewBag.statename = new List<SelectListItem>(){
                new SelectListItem(){ Text = "", Value="Select State"}
            }; ViewBag.RefCityId = new List<SelectListItem>() {
                new SelectListItem(){Text="", Value="Select City"}
            };
            ViewBag.RefDepartmentId = new SelectList(db.Departments, "DepId", "DepName");
            return View();
        }

        public JsonResult GetStatesByCountryId(int id)
        {
            return Json(db.StateMasters.Where(a => a.RefCountryId == id).Select(b => new { b.StateName, b.StateId }).ToList(), JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetCitiesByStateId(int id)

        {
            return Json(db.CityMasters.Where(a => a.RefStateId == id).Select(b => new { b.CityName, b.CityId }).ToList(), JsonRequestBehavior.AllowGet);
        }

        // POST: Admin/ManageJobs/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "JobId,JobName,JobSkills,JobExpirience,JobIsActive,JobDocuments,JobCreatedBy,JobModifiedBy,JobCreatedDate,JobModifiedDate,RefDepartmentId,RefCityId")] ManageJob manageJob, HttpPostedFileBase[] JobDocuments)
        {
            if (ModelState.IsValid)
            {
               
                    var JobCreate = Convert.ToString(Session["name"]);
                    manageJob.JobCreatedBy = JobCreate;
                    manageJob.JobCreatedDate = DateTime.Now;

                string allfl = "";
                foreach(HttpPostedFileBase file in JobDocuments)
                {
                    if(file != null)
                    {
                        var InputFileName = Path.GetFileName(file.FileName);
                        var ServerSavePath = Path.Combine(Server.MapPath("~/Content/Admin/UploadedFiles/") + InputFileName);
                        //Save file to server folder  
                        file.SaveAs(ServerSavePath);
                        //assigning file uploaded status to ViewBag for showing message to user.  
                        ViewBag.UploadStatus = JobDocuments.Count().ToString() + " files uploaded successfully.";
                        allfl += InputFileName + ",";
                    }
                }
                manageJob.JobDocuments = allfl.Remove(allfl.Length - 1, 1);
                    db.ManageJobs.Add(manageJob);
                    db.SaveChanges();
                    return RedirectToAction("Index");
               
            }

           // ViewBag.RefCityId = new SelectList(db.CityMasters, "CityId", "CityName", manageJob.RefCityId);
            ViewBag.RefDepartmentId = new SelectList(db.Departments, "DepId", "DepName", manageJob.RefDepartmentId);
            return View(manageJob);
        }

        // GET: Admin/ManageJobs/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ManageJob manageJob = db.ManageJobs.Find(id);
            if (manageJob == null)
            {
                return HttpNotFound();
            }
            ViewBag.countryname = new SelectList(db.CountryMasters.ToList(), "CountryId", "CountryName");
            ViewBag.statename = new List<SelectListItem>(){
                new SelectListItem(){ Text = "", Value="Select State"}
            }; ViewBag.RefCityId = new List<SelectListItem>() {
                new SelectListItem(){Text="", Value="Select City"}
            };
           // ViewBag.RefCityId = new SelectList(db.CityMasters, "CityId", "CityName", manageJob.RefCityId);
            ViewBag.RefDepartmentId = new SelectList(db.Departments, "DepId", "DepName", manageJob.RefDepartmentId);
            return View(manageJob);
        }

        // POST: Admin/ManageJobs/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "JobId,JobName,JobSkills,JobExpirience,JobIsActive,JobDocuments,JobCreatedBy,JobModifiedBy,JobCreatedDate,JobModifiedDate,RefDepartmentId,RefCityId")] ManageJob manageJob)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    var ModifiedName = Convert.ToString(Session["name"]);
                    manageJob.JobModifiedBy = ModifiedName;
                    manageJob.JobModifiedDate = DateTime.Now;
                    db.Entry(manageJob).State = EntityState.Modified;
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                catch (Exception ex)
                {

                    TempData["err"] = ex.Message;
                }
            }
            ViewBag.RefCityId = new SelectList(db.CityMasters, "CityId", "CityName", manageJob.RefCityId);
            ViewBag.RefDepartmentId = new SelectList(db.Departments, "DepId", "DepName", manageJob.RefDepartmentId);
            return View(manageJob);
        }

        // GET: Admin/ManageJobs/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ManageJob manageJob = db.ManageJobs.Find(id);
            if (manageJob == null)
            {
                return HttpNotFound();
            }
            return View(manageJob);
        }

        // POST: Admin/ManageJobs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            try
            {
                ManageJob manageJob = db.ManageJobs.Find(id);
                db.ManageJobs.Remove(manageJob);
                db.SaveChanges();
            }
            catch (Exception ex)
            {

                TempData["err"] = ex.Message;
            }
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

JobPortal/Areas/User/Controllers/ManageJobsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using JobPortal.Models;
using static JobPortal.FilterConfig;

namespace JobPortal.Areas.User.Controllers
{
    [UserLoginFilter]
    public class ManageJobsController : Controller
    {
        private dbjobportalEntities1 db = new dbjobportalEntities1();

        // GET: User/ManageJobs
        public ActionResult Index()
        {
            var manageJobs = db.ManageJobs.Include(m => m.CityMaster).Include(m => m.Department);
            return View(manageJobs.ToList());
        }

        // GET: User/ManageJobs/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ManageJob manageJob = db.ManageJobs.Find(id);
            if (manageJob == null)
            {
                return HttpNotFound();
            }
            return View(manageJob);
        }

        // GET: User/ManageJobs/Create
        public ActionResult Create()
        {
            ViewBag.RefCityId = new SelectList(db.CityMasters, "CityId", "CityName");
            ViewBag.RefDepartmentId = new SelectList(db.Departments, "DepId", "DepName");
            return View();
        }

        // POST: User/ManageJobs/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "JobId,JobName,JobSkills,JobExpirience,JobIsActive,JobDocuments,JobCreatedBy,JobModifiedBy,JobCreatedDate,JobModifiedDate,RefDepartmentId,RefCityId")] ManageJob manageJob)
        {
            if (ModelState.IsValid)
            {
                db.ManageJobs.Add(manageJob);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.RefCityId = new SelectList(db.CityMasters, "CityId", "CityName", manageJob.RefCityId);
            ViewBag.RefDepartmentId = new SelectList(db.Departments, "DepId", "DepName", manageJob.RefDepartmentId);
            return View(manageJob);
        }

        // GET: User/ManageJobs/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ManageJob manageJob = db.ManageJobs.Find(id);
            if (manageJob == null)
            {
                return HttpNotFound();
            }
            ViewBag.RefCityId = new SelectList(db.CityMasters, "CityId", "CityName", manageJob.RefCityId);
            ViewBag.RefDepartmentId = new SelectList(db.Departments, "DepId", "DepName", manageJob.RefDepartmentId);
            return View(manageJob);
        }

        // POST: User/ManageJobs/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "JobId,JobName,JobSkills,JobExpirience,JobIsActive,JobDocuments,JobCreatedBy,JobModifiedBy,JobCreatedDate,JobModifiedDate,RefDepartmentId,RefCityId")] ManageJob manageJob)
        {
            if (ModelState.IsValid)
            {
                db.Entry(manageJob).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.RefCityId = new SelectList(db.CityMasters, "CityId", "CityName", manageJob.RefCityId);
            ViewBag.RefDepartmentId = new SelectList(db.Departments, "DepId", "DepName", manageJob.RefDepartmentId);
            return View(manageJob);
        }

        // GET: User/ManageJobs/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ManageJob manageJob = db.ManageJobs.Find(id);
            if (manageJob == null)
            {
                return HttpNotFound();
            }
            return View(manageJob);
        }

        // POST: User/ManageJobs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            ManageJob manageJob = db.ManageJobs.Find(id);
            db.ManageJobs.Remove(manageJob);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

JobPortal/Areas/Admin/Views/ManageJobs/Create.cshtml
@model JobPortal.Models.ManageJob

@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_adminlayout.cshtml";
}

<h2>Create</h2>

@using (Html.BeginForm("create","ManageJobs", FormMethod.Post,new { enctype = "multipart/form-data"}))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>ManageJob</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.JobName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.JobName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.JobName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.JobSkills, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.JobSkills, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.JobSkills, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.JobExpirience, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.JobExpirience, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.JobExpirience, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.JobIsActive, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.JobIsActive)
                    @Html.ValidationMessageFor(model => model.JobIsActive, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.JobDocuments, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.JobDocuments, new { htmlAttributes = new { @class = "form-control" , @type="file",@multiple="multiple" } })
                @Html.ValidationMessageFor(model => model.JobDocuments, "", new { @class = "text-danger" })
            </div>
        </div>

        @*<div class="form-group">
            @Html.LabelFor(model => model.JobCreatedBy, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.JobCreatedBy, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.JobCreatedBy, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.JobModifiedBy, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.JobModifiedBy, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.JobModifiedBy, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.JobCreatedDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.JobCreatedDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.JobCreatedDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.JobModifiedDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.JobModifiedDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.JobModifiedDate, "", new { @class = "text-danger" })
            </div>
        </div>*@

        <div class="form-group">
            @Html.LabelFor(model => model.RefDepartmentId, "RefDepartmentId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("RefDepartmentId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.RefDepartmentId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RefCityId, "Select Country", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("countryname", null, "Select Country", htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.RefCityId, "", new { @class = "text-danger" })
            </div>
        </div>



        <div class="form-group">
            @Html.LabelFor(model => model.RefCityId, "Select State", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("statename", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.RefCityId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RefCityId, "Select City", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("RefCityId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.RefCityId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>


<script>
    $(document).ready(function () {
        $("#countryname").change(function () {
           // alert($(this).val());

            var stateurl = "@Url.Action("GetStatesByCountryId","ManageJobs")/" + $(this).val();

            $.getJSON(stateurl, null, function (data) {

                var htmlstate="<option>Select State State</option>"

                $.each(data, function (i, v) {
                    htmlstate += `<option value="${v.StateId}">${v.StateName}</option>`;
                });

                $("#statename").html(htmlstate);
            });
        });


        $("#statename").change(function () {
         //   alert($(this).val());

            var cityurl = "@Url.Action("GetCitiesByStateId","ManageJobs")/" + $(this).val();

            $.getJSON(cityurl, null, function (data) {

                var htmlcity="<option>Select City</option>"

                $.each(data, function (i, v) {
                    htmlcity += `<option value="${v.CityId}">${v.CityName}</option>`;
                });

                $("#RefCityId").html(htmlcity);
            });
        });


    });
</script>

@section Scripts {

    @Scripts.Render("~/bundles/jqueryui")
    @Styles.Render("~/Content/cssjqryUi")

    <script type="text/javascript">
        $(document).ready(function () {
            $('input[type=datetime]').datepicker({
                dateFormat: "dd/M/yy",
                changeMonth: true,
                changeYear: true,
                yearRange: "-60:+0"
            });

        });
    </script>

} 

JobPortal/Areas/Admin/Views/ManageJobs/Edit.cshtml
@model JobPortal.Models.ManageJob

@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_adminlayout.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>ManageJob</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.JobId)

    <div class="form-group">
        @Html.LabelFor(model => model.JobName, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.JobName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.JobName, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.JobSkills, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.JobSkills, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.JobSkills, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.JobExpirience, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.JobExpirience, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.JobExpirience, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.JobIsActive, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <div class="checkbox">
                @Html.EditorFor(model => model.JobIsActive)
                @Html.ValidationMessageFor(model => model.JobIsActive, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.JobDocuments, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.JobDocuments, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.JobDocuments, "", new { @class = "text-danger" })
        </div>
    </div>

    @*<div class="form-group">
            @Html.LabelFor(model => model.JobCreatedBy, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.JobCreatedBy, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.JobCreatedBy, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.JobModifiedBy, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.JobModifiedBy, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.JobModifiedBy, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.JobCreatedDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.JobCreatedDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.JobCreatedDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.JobModifiedDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.JobModifiedDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.JobModifiedDate, "", new { @class = "text-danger" })
            </div>
        </div>*@

    <div class="form-group">
        @Html.LabelFor(model => model.RefCityId, "Select Country", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("countryname", null, "Select Country", htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.RefCityId, "", new { @class = "text-danger" })
        </div>
    </div>



    <div class="form-group">
        @Html.LabelFor(model => model.RefCityId, "Select State", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("statename", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.RefCityId, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.RefCityId, "RefCityId", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("RefCityId", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.RefCityId, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>


<script>
    $(document).ready(function () {
        $("#countryname").change(function () {
           // alert($(this).val());

            var stateurl = "@Url.Action("GetStatesByCountryId","ManageJobs")/" + $(this).val();

            $.getJSON(stateurl, null, function (data) {

                var htmlstate="<option>Select State State</option>"

                $.each(data, function (i, v) {
                    htmlstate += `<option value="${v.StateId}">${v.StateName}</option>`;
                });

                $("#statename").html(htmlstate);
            });
        });


        $("#statename").change(function () {
          //  alert($(this).val());

            var cityurl = "@Url.Action("GetCitiesByStateId","ManageJobs")/" + $(this).val();

            $.getJSON(cityurl, null, function (data) {

                var htmlcity="<option>Select City</option>"

                $.each(data, function (i, v) {
                    htmlcity += `<option value="${v.CityId}">${v.CityName}</option>`;
                });

                $("#RefCityId").html(htmlcity);
            });
        });


    });
</script>