JobPortal/Areas/Admin/Controllers/DashboardController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using static JobPortal.FilterConfig;

namespace JobPortal.Areas.Admin.Controllers
{
    
    public class DashboardController : Controller
    {
        // GET: Admin/Dashboard
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Logout()
        {
            Session.Abandon();
            return RedirectToAction("Login", "AdminLogin");
        }
    }
}

JobPortal/Areas/Admin/Controllers/jobseeksController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.IO;
using iTextSharp.text;
using iTextSharp.text.pdf;
using iTextSharp.tool.xml;
using iTextSharp.text.html.simpleparser;
using JobPortal.Models;
using static JobPortal.FilterConfig;

namespace JobPortal.Areas.Admin.Controllers
{
    [AdminLoginFilter]
    public class jobseeksController : Controller
    {
        private dbjobportalEntities1 db = new dbjobportalEntities1();

        // GET: Admin/jobseeks
        public ActionResult Index()
        {
            var jobseeks = db.jobseeks.Include(j => j.ManageJob).Include(j => j.UserMaster);
            return View(jobseeks.ToList());
        }

        // GET: Admin/jobseeks/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            jobseek jobseek = db.jobseeks.Find(id);
            if (jobseek == null)
            {
                return HttpNotFound();
            }
            return View(jobseek);
        }

        // GET: Admin/jobseeks/Create
        public ActionResult Create()
        {
            ViewBag.RefJobId = new SelectList(db.ManageJobs, "JobId", "JobName");
            ViewBag.RefUserId = new SelectList(db.UserMasters, "UserId", "UserName");
            return View();
        }

        // POST: Admin/jobseeks/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "JobseekId,JobCreatedDate,RefUserId,RefJobId")] jobseek jobseek)
        {
            if (ModelState.IsValid)
            {
                db.jobseeks.Add(jobseek);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.RefJobId = new SelectList(db.ManageJobs, "JobId", "JobName", jobseek.RefJobId);
            ViewBag.RefUserId = new SelectList(db.UserMasters, "UserId", "UserName", jobseek.RefUserId);
            return View(jobseek);
        }

        // GET: Admin/jobseeks/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            jobseek jobseek = db.jobseeks.Find(id);
            if (jobseek == null)
            {
                return HttpNotFound();
            }
            ViewBag.RefJobId = new SelectList(db.ManageJobs, "JobId", "JobName", jobseek.RefJobId);
            ViewBag.RefUserId = new SelectList(db.UserMasters, "UserId", "UserName", jobseek.RefUserId);
            return View(jobseek);
        }

        // POST: Admin/jobseeks/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "JobseekId,JobCreatedDate,RefUserId,RefJobId")] jobseek jobseek)
        {
            if (ModelState.IsValid)
            {
                db.Entry(jobseek).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.RefJobId = new SelectList(db.ManageJobs, "JobId", "JobName", jobseek.RefJobId);
            ViewBag.RefUserId = new SelectList(db.UserMasters, "UserId", "UserName", jobseek.RefUserId);
            return View(jobseek);
        }

        // GET: Admin/jobseeks/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            jobseek jobseek = db.jobseeks.Find(id);
            if (jobseek == null)
            {
                return HttpNotFound();
            }
            return View(jobseek);
        }

        // POST: Admin/jobseeks/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            jobseek jobseek = db.jobseeks.Find(id);
            db.jobseeks.Remove(jobseek);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }


        [HttpPost]
        [ValidateInput(false)]
        public FileResult Export(string GridHtml)
        {
            using (MemoryStream stream = new System.IO.MemoryStream())
            {
                StringReader sr = new StringReader(GridHtml);
                Document pdfDoc = new Document(PageSize.A2);
                PdfWriter writer = PdfWriter.GetInstance(pdfDoc, stream);
                pdfDoc.Open();
                XMLWorkerHelper.GetInstance().ParseXHtml(writer, pdfDoc, sr);
                pdfDoc.Close();
                return File(stream.ToArray(), "application/pdf", "Grid.pdf");
            }
        }
    }



    
}

JobPortal/Areas/Admin/Views/Shared/_adminlayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Edmin</title>
    <link type="text/css" href="~/Content/Admin/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link type="text/css" href="~/Content/Admin/bootstrap/css/bootstrap-responsive.min.css" rel="stylesheet">
    <link type="text/css" href="~/Content/Admin/css/theme.css" rel="stylesheet">
    @*<link type="text/css" href="~/Content/Admin/images/icons/css/font-awesome.css" rel="stylesheet">*@
    @*<link type="text/css" href='http://fonts.googleapis.com/css?family=Open+Sans:400italic,600italic,400,600' rel='stylesheet'>*@
    <script src="~/Content/Admin/scripts/jquery-1.9.1.min.js" type="text/javascript"></script>
    <script src="~/Content/Admin/scripts/jquery-ui-1.10.1.custom.min.js" type="text/javascript"></script>
    <script src="~/Content/Admin/bootstrap/js/bootstrap.min.js" type="text/javascript"></script>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</head>
<body>
    <div class="navbar navbar-fixed-top ">
        <div class="navbar-inner">
            <div class="container">
                <a class="btn btn-navbar" data-toggle="collapse" data-target=".navbar-inverse-collapse">
                    <i class="icon-reorder shaded"></i>
                </a><a class="brand" href="index.html">Admin </a>
                <div class="nav-collapse collapse navbar-inverse-collapse">
                    <ul class="nav nav-icons">
                        <li><a href="#"><i class="icon-envelope"></i></a></li>
                        <li><a href="#"><i class="icon-eye-open"></i></a></li>
                        <li><a href="#"><i class="icon-bar-chart"></i></a></li>
                    </ul>
                    <form class="navbar-search pull-left input-append" action="#">
                        <input type="text" class="span3">
                        <button class="btn" type="button">
                            <i class="icon-search"></i>
                        </button>
                    </form>
                    <ul class="nav pull-right">
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                Dropdown
                                <b class="caret"></b>
                            </a>
                            <ul class="dropdown-menu">
                                <li><a href="#">Item No. 1</a></li>
                                <li><a href="#">Don't Click</a></li>
                                <li class="divider"></li>
                                <li class="nav-header">Example Header</li>
                                <li><a href="#">A Separated link</a></li>
                            </ul>
                        </li>
                        <li><a href="#">Support </a></li>
                        <li class="nav-user dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                <img src="~/Content/Admin/images/user.png" class="nav-avatar" />
                                <b class="caret"></b>
                            </a>
                            <ul class="dropdown-menu">
                                <li><a href="#">Your Profile</a></li>
                                <li><a href="#">Edit Profile</a></li>
                                <li><a href="#">Account Settings</a></li>
                                <li class="divider"></li>
                                <li><a href="@Url.Action("Logout","Dashboard")">Logout</a></li>
                            </ul>
                        </li>
                    </ul>
                </div>
                <!-- /.nav-collapse -->
            </div>
        </div>
        <!-- /navbar-inner -->
    </div>
    <!-- /navbar -->
    <div class="wrapper">
        <div class="container">
            <div class="row">
                <div class="span2">
                    <div class="sidebar">
                        <ul class="widget widget-menu unstyled">
                            <li class="active">
                                <a href="@Url.Action("Index","jobseeks")">
                                    <i class="menu-icon icon-dashboard"></i>Report
                                </a>
                            </li>
                            <li>
                                <a href="@Url.Action("Index","UserMasters")"><i class="menu-icon icon-edit"></i>Manage Users </a>
                            </li>
                            <li>
                                <a href="@Url.Action("Index","ManageJobs")">
                                    <i class="menu-icon icon-edit"></i>Manage Jobs
                                </a>
                            </li>
                            @*<li>
                                <a href="@Url.Action("Create","ProductMasters")">
                                    <i class="menu-icon icon-tasks"></i>Product <b class="label orange pull-right">

                                    </b>
                                </a>
                            </li>*@
                        </ul>
                        <!--/.widget-nav-->
                        <!--/.widget-nav-->
                        <ul class="widget widget-menu unstyled">
                            <li>
                                <a class="collapsed" data-toggle="collapse" href="#togglePages">
                                    <i class="menu-icon icon-cog">
                                    </i><i class="icon-chevron-down pull-right"></i><i class="icon-chevron-up pull-right">
                                    </i>More Pages
                                </a>
                                <ul id="togglePages" class="collapse unstyled">
                                    <li><a href="other-login.html"><i class="icon-inbox"></i>Login </a></li>
                                    <li><a href="other-user-profile.html"><i class="icon-inbox"></i>Profile </a></li>
                                    <li><a href="other-user-listing.html"><i class="icon-inbox"></i>All Users </a></li>
                                </ul>
                            </li>
                            <li><a href="@Url.Action("Logout","Dashboard")"><i class="menu-icon icon-signout"></i>Logout </a></li>
                        </ul>
                    </div>
                    <!--/.sidebar-->
                </div>
                <!--/.span3-->
                <div class="span10">
                    <div class="content">
                       
                        @RenderBody()

                        <!--/.module-->
                    </div>
                    <!--/.content-->
                </div>
                <!--/.span9-->
            </div>
        </div>
        <!--/.container-->
    </div>
    <!--/.wrapper-->
    <div class="footer">
        <div class="container">
            <b class="copyright">&copy; 2019 Admin</b>All rights reserved.
        </div>
    </div>



</body>
</html>